Chore/update particle network
moonbeam-foundation/moonbeam-docs pull request #1019
Opened 2024-11-05 18:00 UTC by soos3d

### Description

A simple update to the Particle tutorial

2024-11-12 16:26 UTC, albertov19 commented
Hey @soos3d  - Currently @themacexpert is in Devcon. Apologies for the delay in the review

2024-11-12 17:37 UTC, soos3d commented
> Hey @soos3d - Currently @themacexpert is in Devcon. Apologies for the delay in the review

No worries, just making sure we don't forget about it :)

2024-11-13 01:41 UTC, themacexpert requested changes
Thanks for PR! This looks great. Just some comments here to align this with our format guidelines. Once these are in, I'll give it a final check and we'll be good to go.

2024-11-13 01:41 UTC, themacexpert commented on builders/integrations/wallets/particle-network.md
> +Find the repository with the full code implementation on the [Particle Network GitHub](https://github.com/Particle-Network/connect-moonbeam-tutorial).
```suggestion
Find the repository with the full code implementation on the [Particle Network GitHub](https://github.com/Particle-Network/connect-moonbeam-tutorial){target=\_blank}.
```

2024-11-13 01:41 UTC, themacexpert commented on builders/integrations/wallets/particle-network.md
> +- **`projectId`** – your project’s unique ID.
```suggestion
- **`projectId`** – your project’s unique ID
```

2024-11-13 01:41 UTC, themacexpert commented on builders/integrations/wallets/particle-network.md
> +- **`clientKey`** – your client-specific key.
```suggestion
- **`clientKey`** – your client-specific key
```

2024-11-13 01:41 UTC, themacexpert commented on builders/integrations/wallets/particle-network.md
> +- **`appId`** – your application ID.
```suggestion
- **`appId`** – your application ID
```

2024-11-13 01:41 UTC, themacexpert commented on builders/integrations/wallets/particle-network.md
> +=== "yarn"
```suggestion
```

2024-11-13 01:41 UTC, themacexpert commented on builders/integrations/wallets/particle-network.md
> +    yarn add @particle-network/connectkit viem@^2 @particle-network/aa ethers
```suggestion
 yarn add @particle-network/connectkit viem@^2 @particle-network/aa ethers
```

2024-11-13 01:41 UTC, themacexpert commented on builders/integrations/wallets/particle-network.md
> +- **Particle Connect**: Particle's flagship Wallet-as-a-Service solution, offering embedded wallets powered by MPC-TSS for smooth, Web2-like onboarding and interactions, with Account Abstraction supp
```suggestion
- **Particle Connect**: Particle's flagship Wallet-as-a-Service solution, offering embedded wallets powered by MPC-TSS for smooth, Web2-like onboarding and interactions, with Account Abstraction support integrated within a single SDK
```

2024-11-13 01:41 UTC, themacexpert commented on builders/integrations/wallets/particle-network.md
> +- **Particle Network Modular [AA Stack](https://docs.particle.network/developers/account-abstraction){target=\_blank}**: Beyond the default EOA-based interactions, Particle also offers a modular AA s
```suggestion
- **Particle Network Modular [AA Stack](https://docs.particle.network/developers/account-abstraction){target=\_blank}**: Beyond the default EOA-based interactions, Particle also offers a modular AA stack for ERC-4337 account abstraction on Moonbeam, allowing flexibility in the smart account, bundler, and paymaster configurations to suit AA-enabled applications
```

2024-11-13 01:41 UTC, themacexpert commented on builders/integrations/wallets/particle-network.md
> +NEXT_PUBLIC_PROJECT_ID='PROJECT_ID'
```suggestion
NEXT_PUBLIC_PROJECT_ID='INSERT_PROJECT_ID'
```

2024-11-13 01:41 UTC, themacexpert commented on builders/integrations/wallets/particle-network.md
> +NEXT_PUBLIC_CLIENT_KEY='CLIENT_KEY'
```suggestion
NEXT_PUBLIC_CLIENT_KEY='INSERT_CLIENT_KEY'
```

2024-11-13 01:41 UTC, themacexpert commented on builders/integrations/wallets/particle-network.md
> +NEXT_PUBLIC_APP_ID='APP_ID'
```suggestion
NEXT_PUBLIC_APP_ID='INSERT_APP_ID'
```

2024-11-13 01:42 UTC, themacexpert commented
> gmgm, any chance we can review this? Thank you!

Thanks for the PR!

2024-11-13 13:18 UTC, soos3d commented
> Thanks for PR! This looks great. Just some comments here to align this with our format guidelines. Once these are in, I'll give it a final check and we'll be good to go.

sounds good! I'll take care of it now

2024-11-13 13:21 UTC, soos3d commented
Reviewed and accepted the suggestions!

2024-11-19 05:13 UTC, themacexpert commented
![Screenshot 2024-11-18 at 9 13 15 PM](https://github.com/user-attachments/assets/a46f4174-f3d3-4d9e-a4ba-746f025fade0)
If you can sort out this bash command then we should be good to go! thx  @soos3d

2024-11-19 13:55 UTC, soos3d commented
> ![Screenshot 2024-11-18 at 9 13 15 PM](https://private-user-images.githubusercontent.com/5834262/387506819-a46f4174-f3d3-4d9e-a4ba-746f025fade0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjQ4MTAsIm5iZiI6MTczMjAyNDUxMCwicGF0aCI6Ii81ODM0MjYyLzM4NzUwNjgxOS1hNDZmNDE3NC1mM2QzLTRkOWUtYTRiYS03NDZmMDI1ZmFkZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTlUMTM1NTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJhNDhhNGVmYmRjODQwZmQ4Yjc2ZWNkNWQxMTk5Yzk0N2IwYjIyODIxZjhkYTNhYmU3M2YxMDE5N2E1ZDM1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hmu3iPkxLH6MN_0y3Z42eLFsZZap1PZAq8Bdp3BCA1M) If you can sort out this bash command then we should be good to go! thx @soos3d

Sorry about that, this last commit should fix it. Please let me know!

2024-11-19 16:44 UTC, themacexpert approved these changes

2024-11-19 16:44 UTC, merged