Runtime-Upgrade-MBA-3400
moonbeam-foundation/moonbeam-docs pull request #1039
Opened 2024-12-10 20:23 UTC by ibbar

### Description

Please explain the changes this PR addresses here.

### Checklist

- [x] I have added a label to this PR 🏷️
- [ ] I have run my changes through Grammarly
- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [ ] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables
- [ ] If this page requires a disclaimer, I have added one

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2024-12-10 22:28 UTC, themacexpert approved these changes
LGTM!

2024-12-10 22:31 UTC, themacexpert requested changes

2024-12-10 22:31 UTC, themacexpert commented on variables.yml
>      parachain_release_tag: v0.41.0 # must be in this exact format for links to work
```suggestion
    parachain_release_tag: v0.42.1 # must be in this exact format for links to work
```

2024-12-10 22:31 UTC, themacexpert commented on variables.yml
>      tracing_tag: moonbeamfoundation/moonbeam-tracing:v0.41.0-3300-d3e6
```suggestion
    tracing_tag: moonbeamfoundation/moonbeam-tracing:v0.42.1-3400-3ebd
```

2024-12-10 22:31 UTC, themacexpert commented on variables.yml
>      parachain_sha256sum: d199266180adcdb25c19aa0ac9d8f5a7157ef1235393fac616d48bb68ba8bcde
```suggestion
    parachain_sha256sum: 9b645b2fd9e575b26ea727e96dc2a81486a73461bb961ba33ea2136e4c9060d8
```

2024-12-10 22:38 UTC, themacexpert approved these changes

2024-12-11 17:50 UTC, eshaben reviewed
Were the links checked that use the `{{ networks.moonbase.spec_version }}` variable?

2024-12-11 21:25 UTC, themacexpert commented
> Were the links checked that use the `{{ networks.moonbase.spec_version }}` variable?

Yup Ibra did

2024-12-11 22:07 UTC, eshaben commented
Nice!! thanks!! 🚀

2024-12-11 22:08 UTC, merged