Freshen up Graph Docs
moonbeam-foundation/moonbeam-docs pull request #1040
Opened 2024-12-17 20:13 UTC by themacexpert

### Description

Refreshes Graph Docs in anticipation of upcoming Marketing announcement. 

### Checklist

- [x] I have added a label to this PR 🏷️
- [ ] I have run my changes through Grammarly
- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [ ] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables
- [ ] If this page requires a disclaimer, I have added one

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2025-01-03 09:11 UTC, ibbar submitted a review, later dismissed
LGTM!

2025-01-06 15:56 UTC, dawnkelly09 requested changes
Thank you for updating. One small request!

2025-01-06 15:56 UTC, dawnkelly09 commented on builders/integrations/indexers/thegraph.md
> +5. Enter the contract address to index and query data from. The CLI will attempt to fetch the ABI from Moonscan. If it doesn't work, make sure that your contract has been verified and retry if needed
Please put the contract address in a code block to give it a copy button for the user. Thanks!

2025-01-06 18:37 UTC, eshaben commented on builders/integrations/indexers/thegraph.md
> +    graph deploy <SUBGRAPH_SLUG>
```suggestion
    graph deploy INSERT_SUBGRAPH_SLUG
```

Not sure why we're not using INSERT_SUBGRAPH_SLUG here, but I think it should be updated

2025-01-10 16:57 UTC, dawnkelly09 approved these changes
🚀  this looks great. Please ensure any needed updates for the Chinese site are addressed or have tickets. Thanks!

2025-01-14 03:09 UTC, merged