Adds EVM contract metadata migration to historical updates page
moonbeam-foundation/moonbeam-docs pull request #1043
Opened 2024-12-18 19:37 UTC by dawnkelly09

### Description

This PR: 
- adds headings ### EVM Pallet and #### EVM Contract Metadata
- adds the EVM Contract Metadata migration information to the historical updates page

### Corresponding PRs

This PR describes changes made here: https://github.com/moonbeam-foundation/moonbeam/pull/2919/files

2024-12-18 22:16 UTC, themacexpert requested changes
Just one thing! ty

2024-12-18 22:16 UTC, themacexpert commented on builders/build/historical-updates.md
> +| Network  | Executed Runtime | Block Applied |
Can you also add the details for Moonriver? This was applied to Moonriver as well :)

2024-12-19 16:23 UTC, themacexpert requested changes

2024-12-19 16:23 UTC, themacexpert commented on builders/build/historical-updates.md
> +| Moonriver |      RT3200      |    8519186    |
```suggestion
| Moonriver |      RT3200      |    8519187    |
```

2024-12-19 16:23 UTC, themacexpert commented on builders/build/historical-updates.md
> +| Moonriver |      RT3200      |    8519186    |
Seems we were off by 1 block on the runtime upgrades page as well... if you update there as well that would be great! 

https://moonriver.subscan.io/block/8519187?tab=event

2024-12-20 19:07 UTC, themacexpert approved these changes
LGTM!

2025-01-06 20:53 UTC, eshaben reviewed
Just a couple questions, but looks good!

2025-01-06 20:53 UTC, eshaben commented on builders/build/historical-updates.md
>  ***
```suggestion
---
```

missed one

2025-01-06 20:53 UTC, eshaben commented on builders/build/runtime-upgrades.md
> +|  [3200](https://forum.moonbeam.network/t/runtime-rt3200-schedule/1881){target=\_blank}   | [7985204](https://moonbeam.subscan.io/block/7985204){target=\_blank} | [8519187](https://moonriver.subscan
Nice find

2025-01-06 20:53 UTC, eshaben commented on builders/build/runtime-upgrades.md
> +|  [3400](https://forum.moonbeam.network/t/runtime-rt3400-schedule/1954){target=\_blank}   |                                  -                                   |                                   -
There might be a merge conflict here, not sure. But there should be an entry for Moonriver now

2025-01-06 20:53 UTC, eshaben commented on builders/build/historical-updates.md
> +This migration was executed at the following runtimes and blocks:
It wasn't applied to Moonbase then?

2025-01-07 21:59 UTC, themacexpert commented
> Cleared the merge conflicts. This should be ready to go pending @themacexpert confirming here: [#1043 (comment)](https://github.com/moonbeam-foundation/moonbeam-docs/pull/1043#discussion_r1905624643)

Correct we did not update Moonbase, only Moonriver and Moonbeam

2025-01-07 22:01 UTC, themacexpert requested changes
@dawnkelly09 Can you please double check that all your changes are included in this PR ? For some reason it is only showing one line of changes... 

<img width="1920" alt="Screenshot 2025-01-07 at 1 58 57 PM" src="https://github.com/user-attachments/assets/b63bea8e-3107-4002-a3b4-5fd8474aa601" />

A similar thing happened to me on https://github.com/moonbeam-foundation/moonbeam-docs/pull/1055 and I just created a new PR.

2025-01-08 21:24 UTC, dawnkelly09 commented
> @dawnkelly09 Can you please double check that all your changes are included in this PR ? For some reason it is only showing one line of changes...
> 
Thank you! I chose the wrong path when clearing merge conflicts I think. Added back with this last commit.

2025-01-08 22:49 UTC, themacexpert requested changes

2025-01-08 22:49 UTC, themacexpert commented on builders/build/historical-updates.md
> +| Moonriver |      RT3200      |    8519186    |
```suggestion
| Moonriver |      RT3200      |    8519187    |
```

2025-01-14 03:09 UTC, merged