feat: add thirdweb
moonbeam-foundation/moonbeam-docs pull request #680
Opened 2023-06-20 17:41 UTC by avneesh0612

hey! I have added how to use Moonbeam with thirdweb in various places. Lmk if you have any questions or the PR needs any changes.

2023-06-21 04:51 UTC, eshaben commented
@avneesh0612 thanks for submitting the PR! I'll check it out and let you know! 🙂

2023-06-26 13:07 UTC, eshaben requested changes
Thank you for opening this PR! This is great! Do you have an SVG of your logo that you could please upload here?

2023-06-26 17:39 UTC, avneesh0612 commented on builders/build/eth-api/dev-env/thirdweb.md
> +npx thirdweb create app --evm
the --evm flag automatically chooses evm

2023-06-26 17:39 UTC, avneesh0612 commented on builders/build/eth-api/dev-env/thirdweb.md
> +   ![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/82077241-a54c-43a1-8aa4-625bc6d52b9b/Untitled.png)
ah yea, forgot to update it. My bad!

2023-06-26 17:39 UTC, avneesh0612 commented on builders/build/eth-api/dev-env/thirdweb.md
> +5. After modifying your contract with your desired custom logic, you may deploy it to Moonbeam using [Deploy](https://portal.thirdweb.com/deploy).
makes sense

2023-06-26 17:39 UTC, avneesh0612 commented on builders/build/eth-api/dev-env/thirdweb.md
> +npx thirdweb deploy --app
hmm, that's weird. Can you provide some more context?

2023-06-26 17:46 UTC, avneesh0612 commented
Here's an svg of the logo: ![thirdweb](https://github.com/PureStake/moonbeam-docs/assets/76690419/4c909061-e945-4530-8a0b-26abfcb04117)

2023-06-28 20:33 UTC, eshaben commented on builders/build/eth-api/dev-env/thirdweb.md
> +npx thirdweb deploy --app
Yeah, I didn't do much. Here are the steps I took:

1. I created an app using `npx thirdweb create app --evm`
2. I installed the dependencies
3. I ran `npx thirdweb deploy --app`

And that's all the steps I took. I tried it again now and I got the same error.

While looking it at it now, I just noticed the deploy script in the `package.json` so I ran `npm run deploy` and that actually worked but the command you specified here does not

2023-06-29 05:01 UTC, avneesh0612 commented on builders/build/eth-api/dev-env/thirdweb.md
> +npx thirdweb deploy --app
ah I see, that is a bug I believe. You are using next, right?

2023-06-29 21:29 UTC, eshaben commented on builders/build/eth-api/dev-env/thirdweb.md
> +npx thirdweb deploy --app
I chose react.. more specifically, it might have been "create react app" and then javascript if i'm remembering correctly

2023-06-29 21:32 UTC, eshaben commented on builders/build/eth-api/dev-env/thirdweb.md
> +npx thirdweb deploy --app
if it's a bug and is going to be fixed we can keep this command here, but maybe also add that they can run `npm run deploy` from within their project directory? not sure, what are your thoughts?

2023-06-30 04:40 UTC, avneesh0612 commented on builders/build/eth-api/dev-env/thirdweb.md
> +npx thirdweb deploy --app
ah yea, that was a bug but it's fixed now! We used the cli directly instead of the script just in case someone didn't use our starter

2023-06-30 15:24 UTC, eshaben commented on builders/build/eth-api/dev-env/thirdweb.md
> +npx thirdweb deploy --app
ok perfect! thank you!

2023-06-30 15:28 UTC, eshaben approved these changes
LGTM! Next step will be to merge this to a local branch where I'll make a few formatting changes to align with the rest of our docs and then we'll merge and publish the page! I'll let you know when the page is live! 🙂

2023-06-30 15:28 UTC, merged

2023-06-30 15:35 UTC, avneesh0612 commented
awesome thanks!