add xcm transactor v3 docs
moonbeam-foundation/moonbeam-docs pull request #743
Opened 2023-09-07 02:37 UTC by eshaben

### Description

This PR adds support and information on the XCM Transactor V3 precompile. 

I tried a new thing to split up the V2 and V3 docs, where I put them into tabs and had text inside of the tabs. We don't typically put plain text inside of tabs, but with the new style of tabs we can easily make a minor css change to make it look good. I'll wait til I get feedback to open a PR in mkdocs, but I did a quick edit in the browser so you can say aye or nay on it 🙂 

<img width="722" alt="Screenshot 2023-09-06 at 10 32 04 PM" src="https://github.com/moonbeam-foundation/moonbeam-docs/assets/26533957/d78deef8-de92-4743-aa8e-1df37ddf735e">

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [x] No additional PRs are required after the translations are done

2023-09-26 10:36 UTC, albertov19 requested changes
Looks good! I pushed a commit with some edits, please check.

I also left a comment

2023-09-26 10:36 UTC, albertov19 commented on builders/interoperability/xcm/xcm-transactor.md
> +=== "V3 (Moonbase Alpha only)"
I don't mind this but can we add a bit of margin here plz

![image](https://github.com/moonbeam-foundation/moonbeam-docs/assets/64150856/4b487d01-aa96-434a-8daf-67e7f46d28dc)

2023-09-27 20:25 UTC, eshaben commented
@albertov19 I merged the PR that adds a margin. This PR is ready to go, just needs one last review, please!

2023-09-29 17:16 UTC, albertov19 approved these changes
LGTM!

2023-09-29 18:44 UTC, merged