add section on overriding local xc-20 transfer gas limits
moonbeam-foundation/moonbeam-docs pull request #744
Opened 2023-09-07 03:59 UTC by eshaben

### Description

This PR adds a new section to the X-Tokens page on overriding the default gas limits for local xc-20 transfers.

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira

### After Translation Requirements

- [x] No additional PRs are required after the translations are done

2023-09-07 21:54 UTC, albertov19 requested changes
Left some minor feedback :)

2023-09-07 21:54 UTC, albertov19 commented on builders/interoperability/xcm/xc20/xtokens.md
> +                // The byte array represents:
We could do it in hexadecimal characters - I believe that is:

`0x6761735F6C696D69743AE0930400000000000000000000000000000000000000`

You basically convert each component of the byte array from Decimal to Hexadecimal and cat them together (I also double check with Chat GPT :)

2023-09-07 21:54 UTC, albertov19 commented on builders/interoperability/xcm/xc20/xtokens.md
> +                // The byte array represents:
the `224, 147, 4, 0` or  `E0 93 04 00` is the actual gas_limit that you are setting here

2023-09-08 06:13 UTC, eshaben commented on builders/interoperability/xcm/xc20/xtokens.md
> +                // The byte array represents:
Yeah I used polkadot utils to test it out and make sure i understood what was going on while creating this as I initially saw it being done like this in the `moonbeam` tests. probably should have just asked chatgpt, would have been much quicker, but at least i feel as though i understand it now 😂

2023-09-08 06:15 UTC, eshaben commented on builders/interoperability/xcm/xc20/xtokens.md
> +                // The byte array represents:
yeah that same hex value checks out for what I have with my script, I'll use that

2023-09-08 16:13 UTC, albertov19 commented
I think maybe we can add an explainer in the code? or at least in the documentation?

2023-09-14 17:09 UTC, eshaben commented
@albertov19 can't re-request your review, but this is ready again!

2023-09-26 10:37 UTC, albertov19 requested changes
Great job!

2023-09-26 10:38 UTC, albertov19 approved these changes
AHHH - Github tricked me and I "requested changes" - I meant approve!

2023-09-26 17:58 UTC, merged