add info on mbip-5 to the key differences section
moonbeam-foundation/moonbeam-docs pull request #749
Opened 2023-09-15 18:16 UTC by eshaben

### Description

This PR adds MBIP-5 to the key differences section of the transaction fees page

### Checklist

- [x] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira

### After Translation Requirements

- [x] No additional PRs are required after the translations are done

2023-09-18 14:17 UTC, themacexpert approved these changes
LGTM 👍

2023-09-26 10:45 UTC, albertov19 requested changes
I think we need to add a bit more and reshuffle this section a bit 🙏

2023-09-26 10:45 UTC, albertov19 commented on builders/get-started/eth-compare/tx-fees.md
> +### Key Differences with Ethereum {: #key-differences-with-ethereum}
I feel that this section should be at the top of the page as an overall Summary. Also MBIP-5 Should have its own section where we show a clear difference from Ethereum. Maybe do a simple contract example where there is a clear contrast in gas estimation on Ethereum and on Moonbeam?

Or maybe  a contract that does provide the same exact gas estiation for a function, but then one very dfferent for another function?

2023-10-06 16:50 UTC, albertov19 approved these changes
LGTM!

Great job on the example it was SUPER clear and easy to follow.

Left a couple of minor suggestions

2023-10-06 16:50 UTC, albertov19 commented on builders/get-started/eth-compare/tx-fees.md
> +The block storage limit prevents transactions in a single block from collectively increasing the storage state by more than 40KB.
Set the block limit as a variable

2023-10-06 16:50 UTC, albertov19 commented on builders/get-started/eth-compare/tx-fees.md
> +Given the block gas limit of 15,000,000 and the block storage limit of 40KB per block, the ratio between gas and storage is 366, which is calculated like this:
Use variables, I think it is more future-proof

2023-10-09 21:17 UTC, merged