Supra Docs
moonbeam-foundation/moonbeam-docs pull request #873
Opened 2024-02-22 17:02 UTC by eshaben

### Description

This PR updates the Supra docs to apply Moonbeam standards and showcases a complete example of interacting with Supra. 

The termynal snippet has text that flows outside of the window, so I created a companion PR for mkdocs that updates the styling so that it wraps to the next line: https://github.com/papermoonio/moonbeam-mkdocs/pull/172

### Checklist

- [x] I have added a label to this PR 🏷️
- [x] I have run my changes through Grammarly
- [x] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [x] If this page requires a disclaimer, I have added one

### After Translation Requirements

- [x] No additional PRs are required after the translations are done

2024-02-22 18:04 UTC, albertov19 requested changes
This one is challenging to go through, but either way, it looks OK from my perspective.

Left some feedback

2024-02-23 00:32 UTC, themacexpert submitted a review, later dismissed
👍

2024-02-23 00:32 UTC, themacexpert commented on builders/integrations/oracles/supra.md
> +=== "Moonbase Alpha"
I noticed that the contracts are verified for Moonbeam but not for Moonbase Alpha. Is it possible for the Supra team to verify these for Moonbase Alpha as well?

2024-02-23 00:32 UTC, themacexpert commented on builders/integrations/oracles/supra.md
> +--8<-- 'text/_disclaimers/third-party-content-intro.md'
IMHO, Is there a way to make the disclaimer smaller, like the bottom of the page? 

It doesn't have to be tiny but maybe a few sizes smaller ? 

<img width="894" alt="Screenshot 2024-02-22 at 4 28 40 PM" src="https://github.com/moonbeam-foundation/moonbeam-docs/assets/5834262/a9771e23-4977-4a17-aee3-44f9fc694d7c">

2024-02-27 15:30 UTC, eshaben commented on builders/integrations/oracles/supra.md
> +    {{ networks.moonbeam.supra.pull_oracle }}
i didn't think so, but i double-checked, and we only do that on the DIA page. I'll reformat this to be a table and add links

2024-03-05 04:42 UTC, eshaben commented
Moved the step-by-step instructions to a tutorial, because it's quite long. So I opted to try and leave the Supra page in the Builders section as more of a quick reference, here's what you need to know, and then link to the tutorial for a deep dive.

2024-03-07 18:08 UTC, albertov19 approved these changes
LGTM! Excellent idea on splitting the things into separate pages!

I also love the new scoped code snippet thingy 🤓

2024-03-08 17:10 UTC, merged