Reorg the builders, precompiles, and pallets sections
moonbeam-foundation/moonbeam-docs pull request #939
Opened 2024-06-10 15:50 UTC by eshaben

### Description

This PR reorganizes the builders section into a higher-level Ethereum / Substrate separation and categorizes the precompiles and pallets sections. Relabeling pallets as low-level interfaces for immediate understanding of what pallets offer.

### Checklist

- [x] I have added a label to this PR 🏷️
- [x] I have run my changes through Grammarly
- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [x] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects

2024-06-11 00:33 UTC, themacexpert requested changes
Just a few broken links everything looks great otherwise!

2024-06-11 00:33 UTC, themacexpert commented on builders/interoperability/xcm/xcm-sdk/v1/xcm-sdk.md
> +In this example, you can use a [Polkadot.js Keyring](/builders/substrate/polkadot-js-api#keyrings){target=\_blank} to sign transactions. Please note that this approach is not recommended for producti
```suggestion
In this example, you can use a [Polkadot.js Keyring](/builders/substrate/libraries/polkadot-js-api#keyrings){target=\_blank} to sign transactions. Please note that this approach is not recommended for production applications.
```

2024-06-11 00:33 UTC, themacexpert commented on builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-precompile.md
> +    - `transactRequiredWeightAtMost` - the weight required to execute the call in the `Transact` instruction. You can get this information by using the [`paymentInfo` method of the Polkadot.js API](/
```suggestion
    - `transactRequiredWeightAtMost` - the weight required to execute the call in the `Transact` instruction. You can get this information by using the [`paymentInfo` method of the Polkadot.js API](/builders/substrate/polkadot-js-api#fees){target=\_blank} on the call
```
```suggestion
    - `transactRequiredWeightAtMost` - the weight required to execute the call in the `Transact` instruction. You can get this information by using the [`paymentInfo` method of the Polkadot.js API](/builders/substrate/libraries/polkadot-js-api#fees){target=\_blank} on the call
```

2024-06-11 00:33 UTC, themacexpert commented on builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-pallet.md
> +        For accurate estimates of the `refTime` and `proofSize` figures for `transactRequiredAtMost`, you can use the [`paymentInfo` method of the Polkadot.js API](/builders/substrate/polkadot-js-api
```suggestion
        For accurate estimates of the `refTime` and `proofSize` figures for `transactRequiredAtMost`, you can use the [`paymentInfo` method of the Polkadot.js API](/builders/substrate/libraries/polkadot-js-api#fees){target=\_blank}.
```

2024-06-11 00:33 UTC, themacexpert commented on builders/ethereum/precompiles/features/governance/preimage.md
> +![Get the proposal hash](/images/builders/ethereum/precompiles/democracy/democracy-5.webp)
This image is missing

2024-06-11 00:33 UTC, themacexpert commented on builders/ethereum/precompiles/features/governance/preimage.md
> +![Get the encoded proposal](/images/builders/ethereum/precompiles/democracy/democracy-6.webp)
This image is missing

2024-06-11 00:33 UTC, themacexpert commented on builders/ethereum/precompiles/features/governance/preimage.md
> +![Add a new preimage](/images/builders/ethereum/precompiles/democracy/democracy-4.webp)
This image is missing

2024-06-11 00:33 UTC, themacexpert commented on builders/ethereum/libraries/ethersrs.md
> +You can view the [complete script on GitHub](https://raw.githubusercontent.com/moonbeam-foundation/moonbeam-docs/master/.snippets/code/builders/ethereum/libraries/ethers-rust/deploy-contract/main.rs)
This link is broken for me but maybe it will be all set once this is merged into master.

2024-06-11 16:20 UTC, albertov19 approved these changes
Amazing job! I'm super sold on the new structure! Love it!

We should replicate this for Tanssi when possible because I think it is very intuitive!

2024-06-12 01:18 UTC, eshaben commented
@themacexpert thank you for such thorough reviews!! Love it!!

2024-06-12 01:21 UTC, themacexpert approved these changes
LGTM 👍

2024-06-12 01:23 UTC, merged