Update the API3 docs
moonbeam-foundation/moonbeam-docs pull request #946
Opened 2024-07-01 15:29 UTC by eshaben

### Description

This PR is an extension of #938. It just cleans up the API3 docs per our documentation standards.

### Checklist

- [x] I have added a label to this PR 🏷️
- [x] I have run my changes through Grammarly

2024-07-02 19:07 UTC, themacexpert requested changes
Looks really good! Just a couple quick things I noticed

2024-07-02 19:07 UTC, themacexpert commented on builders/integrations/oracles/api3.md
There's a couple differences between the Remix comments and the comments on the embedded code. Not a big deal but if we can it would be great to be consistent. 
![Screenshot 2024-07-02 at 2 59 17 PM](https://github.com/moonbeam-foundation/moonbeam-docs/assets/5834262/f2f61be8-d8d7-49e3-b980-50172adc7d9e)

2024-07-02 19:07 UTC, themacexpert commented on builders/integrations/oracles/api3.md
I'd love to see this chart centered, unless there is a new formatting style we follow? 

![Screenshot 2024-07-02 at 3 03 48 PM](https://github.com/moonbeam-foundation/moonbeam-docs/assets/5834262/f7a581ed-3fe3-42c8-af6d-ec65dc540153)

2024-07-02 19:21 UTC, eshaben commented on builders/integrations/oracles/api3.md
Hmmm did you pull in the latest changes to mkdocs? There was a recent PR that was applied that centers the tables

2024-07-02 19:27 UTC, themacexpert commented on builders/integrations/oracles/api3.md
![Screenshot 2024-07-02 at 3 27 37 PM](https://github.com/moonbeam-foundation/moonbeam-docs/assets/5834262/472176bc-43b9-45b0-be7a-f0eb4afe6219)
Looks good 👍

2024-07-12 04:13 UTC, eshaben commented on builders/integrations/oracles/api3.md
Yeah, I wasn't a fan of the periods at the end of their comments and I wanted to add a bit of clarity. But it's their Remix, so I guess I'll rollback my changes

2024-07-24 18:11 UTC, themacexpert approved these changes
LGTM!

2024-07-25 19:43 UTC, merged