Update The Graph docs
moonbeam-foundation/moonbeam-docs pull request #947
Opened 2024-07-02 03:09 UTC by eshaben

### Description

This PR is an extension of #944. It cleans up the docs to meet our standards.

### Checklist

- [x] I have added a label to this PR 🏷️
- [x] I have run my changes through Grammarly
- [x] If this page requires a disclaimer, I have added one

2024-07-02 17:19 UTC, dawnkelly09 commented on builders/integrations/indexers/thegraph.md
> +[The Graph](https://thegraph.com/){target=\_blank} is a decentralized and open-source indexing protocol for querying networks like Ethereum. In short, it provides a way to efficiently store data emit
DApps should be dApps per style guide

2024-07-12 15:00 UTC, dawnkelly09 requested changes
re the suggestion: if user misses the instructions to cd in the terminal (which I did initially...it's a ton of lines flying past!) the rest of the demo work properly.

2024-07-12 17:13 UTC, eshaben commented
@dawnkelly09 done!

2024-07-12 17:47 UTC, dawnkelly09 approved these changes
lgtm

2024-07-12 19:43 UTC, merged