Adding pallet xcm interface precompile
moonbeam-foundation/moonbeam-docs pull request #966
Opened 2024-07-31 13:38 UTC by wuzhong-papermoon

### Description

Adding XCM interface precompile

### Checklist

- [ ✔️] I have added a label to this PR 🏷️
- [ ✔️] I have run my changes through Grammarly
- [ ✔️] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ✔️] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ✔️] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ✔️] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [ ✔️] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ✔️] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables
- [ ✔️] If this page requires a disclaimer, I have added one

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2024-07-31 13:39 UTC, wuzhong-papermoon commented
@eshaben Could you check if the file structure is correct?

2024-08-07 17:49 UTC, themacexpert requested changes
Looks good just a couple things I found!

2024-08-07 17:49 UTC, themacexpert commented on builders/ethereum/precompiles/interoperability/.pages
> +  - 'XCM interface': '/builders/precompiles/xcm-interface/'
```suggestion
  - 'XCM Interface': '/builders/precompiles/xcm-interface/'
```

2024-08-07 17:49 UTC, themacexpert commented on builders/precompiles/xcm-Interface.md
> +??? code "XcmInterface.sol"
```suggestion
??? code "XCMInterface.sol"
```

2024-08-07 17:49 UTC, themacexpert commented on builders/precompiles/xcm-Interface.md
> +1. Get a copy of [`XcmInterface.sol`](https://github.com/Moonsong-Labs/moonkit/blob/main/precompiles/pallet-xcm/XcmInterface.sol){target=\_blank}
```suggestion
1. Get a copy of [`XCMInterface.sol`](https://github.com/Moonsong-Labs/moonkit/blob/main/precompiles/pallet-xcm/XcmInterface.sol){target=\_blank}
```

2024-08-07 17:49 UTC, themacexpert commented on builders/precompiles/xcm-Interface.md
> +2. Paste the file contents into a Remix file named `XcmInterface.sol`
```suggestion
2. Paste the file contents into a Remix file named `XCMInterface.sol`
```

2024-08-07 17:49 UTC, themacexpert commented on builders/precompiles/xcm-Interface.md
> +5. Provide the address of the precompile: `{{networks.moonbeam.precompiles.xcmInterface}}` and click **At Address**
Currently showing as blank for me
<img width="567" alt="Screenshot 2024-08-07 at 10 37 57 AM" src="https://github.com/user-attachments/assets/b89c857a-d71a-47a7-bdf9-7ab946e69b9f">

2024-08-07 17:49 UTC, themacexpert commented on builders/ethereum/precompiles/overview.md
> +    |                               [XCM interface](https://github.com/Moonsong-Labs/moonkit/blob/main/precompiles/pallet-xcm/XcmInterface.sol){target=\_blank}                               |
```suggestion
    |                               [XCM Interface](https://github.com/Moonsong-Labs/moonkit/blob/main/precompiles/pallet-xcm/XcmInterface.sol){target=\_blank}                               |             {{networks.moonbeam.precompiles.xcm_interface}}              |
```

2024-08-07 17:49 UTC, themacexpert commented on builders/ethereum/precompiles/overview.md
> +    |                               [XCM interface](https://github.com/Moonsong-Labs/moonkit/blob/main/precompiles/pallet-xcm/XcmInterface.sol){target=\_blank}                               |
```suggestion
    |                               [XCM Interface](https://github.com/Moonsong-Labs/moonkit/blob/main/precompiles/pallet-xcm/XcmInterface.sol){target=\_blank}                               |             {{networks.moonbeam.precompiles.xcm_interface}}              |
```

2024-08-07 17:49 UTC, themacexpert commented on builders/ethereum/precompiles/overview.md
> +    |                               [XCM interface](https://github.com/Moonsong-Labs/moonkit/blob/main/precompiles/pallet-xcm/XcmInterface.sol){target=\_blank}                               |
```suggestion
    |                               [XCM Interface](https://github.com/Moonsong-Labs/moonkit/blob/main/precompiles/pallet-xcm/XcmInterface.sol){target=\_blank}                               |             {{networks.moonbeam.precompiles.xcm_interface}}              |
```

2024-08-13 03:08 UTC, eshaben reviewed
Looks good! Just some comments on the images:

- The style guide mentions that arrows should not be used with steps. So you can remove the arrows anywhere you're using steps.
- Are the steps 24x24px? This is also outlined in the style guide if you need more info 
- On `xcm-interface-2.webp` the steps appear to be larger than they are on `xcm-interface-3.webp` - can you tell me what size the steps are on 3? I can help you make some decisions here because I realize the size might need to change since they're so close together

As for the structure and where to put things, let me get back to you on this. But it will definitely need to be moved to the Interoperability > XCM section. I'll let you know where exactly!

2024-08-13 03:08 UTC, eshaben commented on builders/precompiles/xcm-Interface.md
> +        - `weight` (Weight memory)- the maximum gas to use in the whole operation. Setting uint64::MAX to `refTime` acts in practice as *unlimited weight*
This is inconsistent with the way we document types on Moonbeam right now. There are some incoming changes, but for now, I think just throw the types into italics (i.e., `paraId` _uint32_, the destination's appchain ID) and that will be a quick win that is close enough

2024-08-13 08:01 UTC, wuzhong-papermoon commented
> Looks good! Just some comments on the images:
> 
> * The style guide mentions that arrows should not be used with steps. So you can remove the arrows anywhere you're using steps.
> * Are the steps 24x24px? This is also outlined in the style guide if you need more info
> * On `xcm-interface-2.webp` the steps appear to be larger than they are on `xcm-interface-3.webp` - can you tell me what size the steps are on 3? I can help you make some decisions here because I realize the size might need to change since they're so close together
> 
> As for the structure and where to put things, let me get back to you on this. But it will definitely need to be moved to the Interoperability > XCM section. I'll let you know where exactly!

Ah sorry that I didn't use standard style for steps. It should be all set now. 24x24 might be alright, would you take a look at the new images? @eshaben

2024-08-13 18:47 UTC, eshaben commented
@wuzhong-papermoon yes, images look better! thanks!

2024-08-16 02:48 UTC, eshaben approved these changes
LGTM! @themacexpert just up to you to review/approve now 🙂

2024-08-21 17:31 UTC, themacexpert approved these changes

2024-08-21 18:52 UTC, merged