Modernize Wormhole Docs
moonbeam-foundation/moonbeam-docs pull request #970
Opened 2024-08-02 00:05 UTC by themacexpert

### Description

Brings Wormhole Docs up to modern docs standards.

### Checklist

- [ ] I have added a label to this PR 🏷️
- [ ] I have run my changes through Grammarly
- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [ ] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables
- [ ] If this page requires a disclaimer, I have added one

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2024-08-08 18:37 UTC, dawnkelly09 requested changes
See my comment about the link to the Moonbeam page on Wormhole needing updated. All of your changes to the images, etc. here look good.

2024-08-08 18:37 UTC, dawnkelly09 commented on builders/interoperability/protocols/wormhole.md
The link under ### Contracts opens to the generic EVM page for Moonbeam. They have something set where it strips the '#moonbeam' from the URL while the page is loading. This link opens to the Moonbeam reference page on Wormhole docs. I can't use 'suggest' for this because it isn't part of this PR's reviewable changes. 

https://docs.wormhole.com/wormhole/reference/blockchain-environments/evm#moonbeam

2024-08-08 21:25 UTC, themacexpert commented on builders/interoperability/protocols/wormhole.md
Good calls! Thank you, fixed!

2024-08-12 15:12 UTC, dawnkelly09 submitted a review, later dismissed
Looks great, Kevin. Thank you!

2024-08-13 03:16 UTC, eshaben requested changes
Awesome! Thanks!

One thing: can you please rename `wormhole-8.webp` to `wormhole-6.webp` so the images are in order?

2024-08-13 20:34 UTC, eshaben approved these changes
Ah thanks for fixing the other images! LGTM! ✨

2024-08-13 20:35 UTC, merged