adds moon_getLatestSyncedBlock to moonbeam custom API methods
moonbeam-foundation/moonbeam-docs pull request #974
Opened 2024-08-05 20:24 UTC by dawnkelly09

### Description

- adds moon_getLatestSyncedBlock to moonbeam custom API methods
- includes curl example script

### Checklist

- [ x ] I have added a label to this PR 🏷️
- [ ] I have run my changes through Grammarly
- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [ ] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables
- [ ] If this page requires a disclaimer, I have added one

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2024-08-07 16:27 UTC, themacexpert requested changes

2024-08-07 16:27 UTC, themacexpert commented on builders/ethereum/json-rpc/moonbeam-custom-api.md
> +Moonbeam nodes include support for custom JSON-RPC endpoints:
```suggestion
Moonbeam nodes include support for custom JSON-RPC endpoints: 

```

2024-08-07 16:27 UTC, themacexpert commented on builders/ethereum/json-rpc/moonbeam-custom-api.md
> +Moonbeam nodes include support for custom JSON-RPC endpoints:
<img width="979" alt="Screenshot 2024-08-07 at 9 21 56 AM" src="https://github.com/user-attachments/assets/2ef80b42-e82a-43fb-8171-26aad44eca4a">
Currently looks like this but the extra line should fix it.

2024-08-07 16:27 UTC, themacexpert commented on builders/ethereum/json-rpc/moonbeam-custom-api.md
> +    === "Returns"
Also want to mention the data type that is being returned, in this case, an integer

2024-08-08 21:12 UTC, themacexpert approved these changes
LGTM!

2024-08-13 03:21 UTC, eshaben commented
Thank you both!

2024-08-13 03:21 UTC, merged