Add radium block provider to RPC endpoints page
moonbeam-foundation/moonbeam-docs pull request #996
Opened 2024-09-23 12:56 UTC by kapetan3sid

### Description

Please explain the changes this PR addresses here.

### Checklist

- [ ] I have added a label to this PR 🏷️
- [ ] I have run my changes through Grammarly
- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [ ] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables
- [ ] If this page requires a disclaimer, I have added one

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2024-09-24 14:11 UTC, themacexpert requested changes
Is RadiumBlock a public endpoint? I get these errors whenever I try to query a method like getBalance or estimateGas: 

`<html>

<head>
    <title>403 Forbidden</title>
</head>

<body>
    <center>
        <h1>403 Forbidden</h1>
    </center>
    <hr>
    <center>openresty/1.25.3.2</center>
</body>

</html>`

2024-09-24 15:54 UTC, themacexpert requested changes
Added changes

2024-09-24 15:54 UTC, themacexpert commented on .snippets/text/builders/get-started/endpoints/moonbeam.md
> +     |  RadiumBlock  |                       <pre>```https://moonbeam.public.curie.radiumblock.co```</pre>                        | 200 req/sec   |
```suggestion
     |  RadiumBlock  |                       <pre>```https://moonbeam.public.curie.radiumblock.co/http```</pre>                        | 200 req/sec   |
```

2024-09-24 15:54 UTC, themacexpert commented on .snippets/text/builders/get-started/endpoints/moonriver.md
> +      |  RadiumBlock  |                       <pre>```https://moonriver.public.curie.radiumblock.co```</pre>                        | 200 req/sec |
```suggestion
      |  RadiumBlock  |                       <pre>```https://moonriver.public.curie.radiumblock.co/http```</pre>                        | 200 req/sec |
```

2024-09-24 15:54 UTC, themacexpert commented on .snippets/text/builders/get-started/endpoints/moonriver.md
> +      | RadiumBlock |<pre>```wss://moonriver.public.curie.radiumblock.co```</pre>        | 200 req/sec |
```suggestion
      | RadiumBlock |<pre>```wss://moonriver.public.curie.radiumblock.co/ws```</pre>        | 200 req/sec |
```

2024-09-24 15:54 UTC, themacexpert commented on .snippets/text/builders/get-started/endpoints/moonbeam.md
> +    | RadiumBlock |       <pre>```wss://moonbeam.public.curie.radiumblock.co```</pre>       | 200 req/sec |
```suggestion
    | RadiumBlock |       <pre>```wss://moonbeam.public.curie.radiumblock.co/ws```</pre>       | 200 req/sec |
```

2024-09-24 23:47 UTC, eshaben commented
Drive by comment: I'd love to see the tables formatted after the suggestions have been added 🙂 🚗

2024-09-25 14:05 UTC, themacexpert approved these changes
LGTM

2024-09-25 14:08 UTC, merged